// MaDenFlow 5.0 — основной движок
console.log("MaDenFlow 5.0 запущен 🚀");
const planner=document.getElementById("planner"),weekTitle=document.getElementById("weekTitle");
const weekDays=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"];
let currentDate=new Date(),selectedDate=null,calendarCursor=new Date();
function getMonday(date){const d=new Date(date);let day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d}
function localKey(d){return localDateKey(d)}
function renderWeek(){planner.innerHTML="";const monday=getMonday(currentDate),sunday=new Date(monday);sunday.setDate(monday.getDate()+6);weekTitle.textContent=`${monday.toLocaleDateString("ru-RU")} — ${sunday.toLocaleDateString("ru-RU")}`;let maxTasks=0;for(let i=0;i<7;i++){const date=new Date(monday);date.setDate(monday.getDate()+i);maxTasks=Math.max(maxTasks,getTasks(localKey(date)).length);const key=localKey(date);const section=document.createElement("section");section.className="day"+(date.getDay()===0||date.getDay()===6?" weekend":"");if(date.toDateString()===new Date().toDateString())section.classList.add("today");section.dataset.date=key;section.innerHTML=`<div class="day-title"><div class="day-name"><span class="day-weekday">${weekDays[i]}</span> ${date.getDate()} <span class="day-month">${date.toLocaleDateString("ru-RU",{month:"short"}).replace(".","")}</span> <span class="day-status" data-date="${key}">⚪</span>${date.toDateString()===new Date().toDateString()?" ⭐":""}</div><button class="add-task-day" data-date="${key}">＋</button></div><div class="day-content"><div class="tasks"></div></div>`;planner.appendChild(section);loadTasks(key,section.querySelector(".tasks"))}planner.classList.remove("week-normal","week-compact","week-ultra");planner.classList.add(maxTasks>=7?"week-ultra":maxTasks>=4?"week-compact":"week-normal");updateDayStatus();activateDays();activateAddButtons()}
function activateDays(){document.querySelectorAll(".day-title").forEach(title=>title.onclick=e=>{if(e.target.closest(".add-task-day"))return;const day=title.closest(".day");selectedDate=day.dataset.date;document.querySelectorAll(".day").forEach(x=>x.classList.remove("selected-day"));day.classList.add("selected-day")})}
function activateAddButtons(){document.querySelectorAll(".add-task-day").forEach(btn=>btn.onclick=e=>{e.stopPropagation();selectedDate=btn.dataset.date;openTaskModal()})}
function openTaskModal(){const modal=document.getElementById("taskModal");modal.dataset.editDate="";modal.dataset.editIndex="";document.getElementById("taskModalTitle").textContent="Новая задача";document.getElementById("newTaskInput").value="";document.getElementById("newTaskTime").value="";document.getElementById("repeatTask").checked=false;document.getElementById("repeatOptions").classList.add("hidden");document.getElementById("recurrenceBox").classList.remove("hidden");const d=new Date(selectedDate+"T12:00:00");const until=new Date(d);until.setFullYear(until.getFullYear()+1);document.getElementById("repeatUntil").value=localKey(until);modal.classList.remove("hidden");document.getElementById("newTaskInput").focus()}
document.getElementById("repeatTask").onchange=e=>document.getElementById("repeatOptions").classList.toggle("hidden",!e.target.checked);
document.getElementById("saveTaskBtn").onclick=()=>{if(!selectedDate)return;const modal=document.getElementById("taskModal"),input=document.getElementById("newTaskInput"),time=document.getElementById("newTaskTime"),text=input.value.trim();if(!text)return;const editDate=modal.dataset.editDate,editIndex=modal.dataset.editIndex;if(editDate!==""&&editIndex!==""){editTask(editDate,Number(editIndex),text,time.value);modal.classList.add("hidden");renderWeek();return}if(document.getElementById("repeatTask").checked)addRecurringTask(selectedDate,text,document.getElementById("repeatType").value,document.getElementById("repeatUntil").value,time.value);else addTask(selectedDate,text,{time:time.value});modal.classList.add("hidden");renderWeek()};
document.getElementById("cancelTaskBtn").onclick=()=>{const m=document.getElementById("taskModal");m.classList.add("hidden");m.dataset.editDate="";m.dataset.editIndex=""};
document.getElementById("prevWeek").onclick=()=>changeWeek(-1);document.getElementById("nextWeek").onclick=()=>changeWeek(1);document.getElementById("todayBtn").onclick=()=>{currentDate=new Date();renderWeek()};
function changeWeek(n){currentDate.setDate(currentDate.getDate()+n*7);renderWeek()}
let touchStartX=0,touchStartY=0;planner.addEventListener("touchstart",e=>{touchStartX=e.changedTouches[0].screenX;touchStartY=e.changedTouches[0].screenY},{passive:true});planner.addEventListener("touchend",e=>{const dx=e.changedTouches[0].screenX-touchStartX,dy=e.changedTouches[0].screenY-touchStartY;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.2)changeWeek(dx<0?1:-1);resetUITimer()},{passive:true});
function updateDayStatus(){document.querySelectorAll(".day-status").forEach(s=>{const list=getTasks(s.dataset.date)||[];s.textContent=!list.length?"⚪":list.every(x=>x.done)?"🟢":"🟡"})}
// Календарь
function openCalendar(){calendarCursor=new Date(currentDate);renderCalendar();document.getElementById("calendarModal").classList.remove("hidden")}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();document.getElementById("calendarTitle").textContent=new Date(y,m,1).toLocaleDateString("ru-RU",{month:"long",year:"numeric"});const grid=document.getElementById("calendarGrid");grid.innerHTML=weekDays.map(d=>`<div class="cal-weekday">${d}</div>`).join("");const first=(new Date(y,m,1).getDay()||7)-1,days=new Date(y,m+1,0).getDate();for(let i=0;i<first;i++)grid.insertAdjacentHTML("beforeend",`<div class="cal-empty"></div>`);for(let day=1;day<=days;day++){const d=new Date(y,m,day),key=localKey(d),btn=document.createElement("button");btn.className="cal-day";if(d.toDateString()===new Date().toDateString())btn.classList.add("today");if(d>=getMonday(currentDate)&&d<=new Date(getMonday(currentDate).getFullYear(),getMonday(currentDate).getMonth(),getMonday(currentDate).getDate()+6))btn.classList.add("in-week");btn.textContent=day;btn.onclick=()=>{currentDate=d;renderWeek();document.getElementById("calendarModal").classList.add("hidden")};grid.appendChild(btn)}}
document.getElementById("calendarBtn").onclick=openCalendar;document.getElementById("calendarPrev").onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};document.getElementById("calendarNext").onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()};document.getElementById("calendarToday").onclick=()=>{currentDate=new Date();renderWeek();document.getElementById("calendarModal").classList.add("hidden")};document.getElementById("calendarClose").onclick=()=>document.getElementById("calendarModal").classList.add("hidden");
// Служение
 document.getElementById("serviceBtn").onclick=()=>openService(localKey(currentDate).slice(0,7));
// Настройки
const settingsModal=document.getElementById("settingsModal");function openSettings(){document.getElementById("darkModeToggle").checked=!!appData.settings.darkMode;document.getElementById("accountEmail").value=appData.settings.email||"";document.getElementById("accountStatus").textContent=appData.settings.email?`Email сохранён: ${appData.settings.email}`:"Email не подключён";settingsModal.classList.remove("hidden")}
document.getElementById("settingsBtn").onclick=openSettings;document.getElementById("settingsClose").onclick=()=>settingsModal.classList.add("hidden");document.getElementById("darkModeToggle").onchange=e=>{appData.settings.darkMode=e.target.checked;document.body.classList.toggle("dark",e.target.checked);saveStorage()};document.getElementById("saveEmailBtn").onclick=()=>{const email=document.getElementById("accountEmail").value.trim();if(email&&!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)){alert("Введите корректный email");return}appData.settings.email=email;saveStorage();document.getElementById("accountStatus").textContent=email?`Email сохранён: ${email}`:"Email не подключён"};
document.getElementById("exportDataBtn").onclick=()=>{const blob=new Blob([JSON.stringify(appData,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`MaDenFlow_backup_${localKey(new Date())}.json`;a.click();URL.revokeObjectURL(a.href)};document.getElementById("importDataBtn").onclick=()=>document.getElementById("importDataFile").click();document.getElementById("importDataFile").onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data||typeof data!=="object"||!data.tasks||!data.service)throw new Error();localStorage.setItem("MaDenFlow_data",JSON.stringify(data));location.reload()}catch(err){alert("Не удалось восстановить резервную копию.")}};reader.readAsText(file)};
// Автоскрытие: тач/скролл не раскрывают шапку. Ручка снизу раскрывает.
let uiTimer;const body=document.body,topHandle=document.getElementById("topHandle");function hideUI(){body.classList.add("ui-hidden")}function resetUITimer(){clearTimeout(uiTimer);uiTimer=setTimeout(hideUI,5000)}function showUI(){body.classList.remove("ui-hidden");clearTimeout(uiTimer);uiTimer=setTimeout(hideUI,5000)}topHandle.onclick=showUI;document.addEventListener("pointerdown",e=>{if(e.target.closest("button,input,.modal,.task-menu"))return;resetUITimer()},{passive:true});
// старт
document.body.classList.add("app-enter");setTimeout(()=>document.body.classList.add("app-ready"),650);
if(appData.settings.darkMode)document.body.classList.add("dark");renderWeek();resetUITimer();
window.renderWeek=renderWeek;window.updateDayStatus=updateDayStatus;window.changeWeek=changeWeek;