// MaDenFlow Service 5.0
let currentServiceMonth="";
function monthLabel(key){const [y,m]=key.split("-").map(Number);return new Date(y,m-1,1).toLocaleDateString("ru-RU",{month:"long",year:"numeric"})}
function shiftMonth(key,delta){const [y,m]=key.split("-").map(Number);const d=new Date(y,m-1+delta,1);return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")}
function formatTotal(t){return `${t.hours} ч ${String(t.minutes).padStart(2,"0")} мин`}
function openService(month){currentServiceMonth=month;document.getElementById("serviceMonth").textContent=monthLabel(month);const list=document.getElementById("serviceList");list.innerHTML="";getServiceMonth(month).sort((a,b)=>a.date.localeCompare(b.date)).forEach((item,index)=>{const row=document.createElement("div");row.className="service-row";row.innerHTML=`<div class="service-date">${item.date}</div><div class="service-time">${item.hours} ч ${String(item.minutes).padStart(2,"0")} мин</div>`;row.onclick=()=>showServiceMenu(index);list.appendChild(row)});document.getElementById("serviceTotal").textContent=formatTotal(getServiceTotal(month));document.getElementById("serviceGrandTotal").textContent=formatTotal(getServiceGrandTotal());document.getElementById("serviceModal").classList.remove("hidden")}
function closeService(){document.getElementById("serviceModal").classList.add("hidden")}
function openAddService(){document.getElementById("serviceAddModal").classList.remove("hidden");const d=new Date();document.getElementById("serviceDate").value=localDateKey(d);document.getElementById("serviceHours").value="";document.getElementById("serviceMinutes").value=""}
function closeAddService(){document.getElementById("serviceAddModal").classList.add("hidden")}
function saveServiceRecord(){const date=document.getElementById("serviceDate").value;const hours=Number(document.getElementById("serviceHours").value)||0;const minutes=Number(document.getElementById("serviceMinutes").value)||0;if(!date||hours===0&&minutes===0){alert(!date?"Укажите дату.":"Введите время.");return}const month=date.slice(0,7);addServiceRecord(month,{date,hours,minutes});closeAddService();openService(month)}
function showServiceMenu(index){const records=getServiceMonth(currentServiceMonth);const record=records[index];if(!record)return;const action=prompt("1 — Изменить\n2 — Удалить");if(action==="1"){const date=prompt("Дата",record.date);if(date===null)return;const hours=prompt("Часы",record.hours);if(hours===null)return;const minutes=prompt("Минуты",record.minutes);if(minutes===null)return;editServiceRecord(currentServiceMonth,index,{date,hours,minutes});openService(currentServiceMonth)}else if(action==="2"&&confirm("Удалить запись?")){deleteServiceRecord(currentServiceMonth,index);openService(currentServiceMonth)}}
document.getElementById("addServiceBtn").onclick=openAddService;document.getElementById("closeServiceBtn").onclick=closeService;document.getElementById("saveServiceBtn").onclick=saveServiceRecord;document.getElementById("cancelServiceBtn").onclick=closeAddService;document.getElementById("servicePrevMonth").onclick=()=>openService(shiftMonth(currentServiceMonth,-1));document.getElementById("serviceNextMonth").onclick=()=>openService(shiftMonth(currentServiceMonth,1));
function refreshService(){if(currentServiceMonth)openService(currentServiceMonth)}
window.openService=openService;window.closeService=closeService;window.openAddService=openAddService;window.closeAddService=closeAddService;window.saveServiceRecord=saveServiceRecord;window.showServiceMenu=showServiceMenu;window.refreshService=refreshService;